#+TITLE:  Kritiikki – tietokantasovellus kirja-arvioille
#+DRAWERS: 
#+AUTHOR: Tapio Ikkala
#+OPTIONS: H:5  toc:t  num:t tags:nil
#+BABEL: :results output :session
#+LATEX_CMD: xelatex
#+LATEX_CLASS: memarticle
#+LATEX_HEADER: \renewcommand{\thesection}{\arabic{section}}
*** Johdanto
Kritiikki-kirja-arviosovellus on esimerkiksi kirjallisuudesta kiinnostuneen kaveriporukan käyttöön suunniteltu sovellus, jonka avulla on helppo jakaa tietoa siitä, mitä kukin on lukenut ja pitänyt lukemastaan. 

Sovellus toteutetaan web-sovelluksena laitoksen users-palvelimella Apache Tomcatin avulla. Sovellus toteutetaan Javalla ja tietokantakielenä käytetään PostgreSQL:ää.
*** Yleiskuva järjestelmästä
Järjestelmässä on kaksi käyttäjätyyppiä: tavallinen käyttäjä ja ylläpitäjä. Tavallisen käyttäjän oikeuksien lisäksi ylläpitäjällä on oikeus poistaa muiden käyttäjien tilejä sekä kirjoihin liittyviä tietoja. 

Kaikki käyttäjät voivat lisätä järjestelmään kirjoja sekä antaa niille numeerisia arvosteluja tai kirjoittaa kritiikkejä. Kritiikkeihin on myös mahdollista kirjoittaa kommentteja. Lisäksi järjestelmän avulla on mahdollista tutkia, millaisia kirjoja järjestelmän käyttäjät ovat lukeneet ja miten kirjoja on arvioitu.

#+BEGIN_LATEX
\begin{figure}[h]
\begin{center}
\includegraphics[width=1\textwidth]{/home/tapio/kritiikki/doc/käyttötapauskaavio.png}
\\ Käyttötapauskaavio
\end{center}
\end{figure}
#+END_LATEX

**** Käyttäjäryhmät
- Tavallinen käyttäjä:
Tavallisella käyttäjällä tarkoitetaan kaikkia käyttäjiä, jotka ovat rekisteröityneet palveluun ja joilla ei ole ylläpitäjän oikeuksia.

- Ylläpitäjä:
Ylläpitäjä vastaa järjestelmän ylläpidosta. Usealla käyttäjällä voi olla ylläpito-oikeudet. Ylläpitäjä voi tehdä järjestelmässä samat toiminnot kuin muutkin käyttäjät, minkä lisäksi hän pystyy poistamaan käyttäjiä ja muuta tietosisältöä järjestelmästä.

**** Käyttötapauskuvaukset
- Rekisteröityminen:
Palveluun vielä rekisteröitymätön käyttäjä klikkaa kirjautumissivun Rekisteröidy-linkkiä, joka vie hänet rekisteröitymissivulle. Käyttäjä täyttää vaaidtut tiedot ja klikkaa lopuksi Lähetä-nappia.

- Kirjautuminen

- Kirjan lisääminen:
Käyttäjä kirjautuu palveluun omilla tunnuksillaan. Hän painaa etusivulla sijaitsevaa Lisää-nappia, joka vie hänet lomakesivulle, jolla kirjan lisääminen tapahtuu. Käyttäjä syötää kirjan ja kirjalijan nimen, ilmestymisvuoden, ilmestymiskielen, kustantajan ja sivunumeron. Halutessan käyttäjä voi antaa kirjalle myös numeroavosanan asteikolla 4-10,  kirjoittaa siitä kritiikin ja ladata järjestelmään kirjan kasikuvan.

- Kirjan tietojen muokkaus:
Käyttäjä kirjautuu palveluun omilla tunnuksillaan. Hän klikkaa kirjalistasta kirjaa, jonka tietoja hän haluaa muokata (esim. korjata väärän vuosiluvun oikeaksi). Klikkaus avaa kirjan tietosivun, jolla tietoja on mahdollista muokata. Käyttäjä painaa 

- Kirjan arviointi:
Käyttäjä kirjautuu palveluun omilla tunnuksillaan. Käyttäjä hakee järjestelmästä kirjan, jonka hän haluaa arvioida. Klikkaamalla kirjaa hän vie itsensä sivulle, joka näyttää kirjaan liittyvät tiedot ja mahdollistaa numeroarvosanana välillä 4-10 syöttämisen, jos käyttäjä ei vielä ole arvioinut kirjaa.

- Kritiikin kirjoittaminen:
Käyttäjä kirjautuu palveluun omilla tunnuksillaan. Käyttäjä hakee järjestelmästä kirjan, jonka hän haluaa arvioida. Klikattuaan kirjaa hänelle aukeaa näkymä kirjaan liittyviin tietoihin sekä tekstikenttään, johon hän voi itse kirjoittaa. Teksti tallennettaan järjestelmään painamalla Lähetä-nappia.

- Kritiikin kommentointi:
Käyttäjä haluaa kommentoida jonkin toisen kirjoittamaa kritiikkiä. Hän painaa kritiikin lopussa olevaa Kommentoi-nappia, jolloin aukeaa tekstikenttä kommenttia varten. Käyttäjä kirjoittaa kommenttinsa tekstikenttään ja painaa lopuksi Lähetä-nappia, jolloin kommentti tallentuu järjestelmään.

- Kritiikin/kommentin editointi:
Käyttäjää haluaa korjata tekemänsä virheen kritiikkiin/kommenttiin. Hän painaa kirjoittamansa kritiikin lopussa olevaa Edit-nappulaa (näkyvillä vain kritiikin kirjoittaneelle käyttäjälle), tekee korjauksen ja painaa lopuksi Lähetä.

- Käyttäjätilin poisto: (ylläpitäjä)
Ylläpitäjä siirtyy vain ylläpitäjän oikeuksilla varustetuille käyttäjille näkyvälle Käyttäjät-välilehdelle, jossa hänelle aukeaa lista palvelun käyttäjistä sekä hakukenttä tietyn käyttäjän etsimiseksi. Ylläpitäjä klikkaa käyttäjää, ja valitsee avautuvasta "Haluatko poistaa tämän käyttäjän? Kyllä/Ei" -valikosta Kyllä.

- Kirjan/kirjoihin liittyvän tiedon poisto (ylläpitäjä)
Ylläpitäjä etsii etusivulta kirjan, jonka tietoja hän haluaa muokata. Hän klikkaa kirjaa, jolloin hän siirtyy kirjan tietosivulle. Ylläpitäjällä on tietosivulla näkymässä Poista-nappi, jota klikkaamalla voi poistaa kirja.

#+LATEX: \newpage
*** Järjestelmän tietosisältö

#+BEGIN_LATEX
\begin{figure}[h]
\begin{center}
\includegraphics[width=1\textwidth]{/home/tapio/kritiikki/doc/kasitekaavio.png}
\\ Käsitekaavio
\end{center}
\end{figure}
#+END_LATEX

- Tietokohde: Kirja

#+ATTR_LaTeX: align=llp{3cm}rl
| Atrribuutti          | Arvojoukko           | Kuvailu              |
|----------------------+----------------------+----------------------|
| <20>                 | <20>                 | <20>                 |
| Id                   | int                  | Yksilöllinen tunnus  |
| Nimi                 | Merkkijono, max 100 mer. | Kirjan nimi          |
| Kirjailija           | Merkkijono, max 100 mer. | Sukunimi, Etunimi    |
| Julkaisuvuosi        | Merkkijono, max 4 merk. | Julkaisuvuosi, xxxx  |
| Julkaisukieli        | Merkkijono, max 50 merk. | Teoksen alkuperäiskieli |
| Suomentaja           | Merrijoon, max 100 merk. | Skukunimi, Etunimi   |

#+LATEX: \noindent
Automaattisesti luotavan Id:nlisäksi kirjan pakollisia attribuutteja on kirjan ja kirjailijan nimi. Muiden attribuuttien arvona voi olla null.

- Tietokohde: Kritiikki

#+ATTR_LaTeX: align=llp{3cm}rl
| Atrribuutti          | Arvojoukko           | Kuvailu              |
|----------------------+----------------------+----------------------|
| <20>                 | <20>                 | <20>                 |
| Kritiikki            | Merkkijono, max 10 000 merk. | Kritiikiteksti       |
| Otiskko              | Merkkijono, max 100 merk. | Kritiikin otsikko    |
| Id                   | Kokonaisluku         | Yksilöllinen tunnus  |

#+LATEX: \noindent
Kritiiin attribuutit ovat itse kritiikki, kritiikin otsikko sekä automaattisesti generoituva id. Kritiikki liittyy aina tasan yhteen kirjaan.

- Tietokohde: Kommentti

#+ATTR_LaTeX: align=llp{3cm}rl
| Atrribuutti          | Arvojoukko           | Kuvailu              |
|----------------------+----------------------+----------------------|
| <20>                 | <20>                 | <20>                 |
| Kommentti            | Merkkijono, max 5000 merk. | Kommenttiteksti      |
| Id                   | Kokonaisluku         | Yksilöllinen tunnus  |

#+LATEX: \noindent
Kommentin attribuutit ovat kommenttiteksti sekä autmaattisesti generoituva id. Kommentti liityy aina yhteen kritiikkiin ja kirjoittajaan.

- Tietokohde: Käyttäjä

#+ATTR_LaTeX: align=llp{3cm}rl
| Atrribuutti          | Arvojoukko           | Kuvailu              |
|----------------------+----------------------+----------------------|
| <20>                 | <20>                 | <20>                 |
| Id                   | Merkkijono, max 100 merk. | Yksilöllinen käyttäjätunnus |
| Sähköpostiosoite     | Merkkijono, max 200 merk. | Käyttäjän sposti     |
| Salasana             | Merkkijono, max 100 merk. | Salasana             |

#+LATEX: \noindent
Käyttäjän attribuutit ovat yksilöllinen käyttäjätunnus, salasan ja sähköpostiosoite.

- Tietokohde: Pisteet

#+ATTR_LaTeX: align=llp{3cm}rl
| Atrribuutti          | Arvojoukko           | Kuvailu              |
|----------------------+----------------------+----------------------|
| <20>                 | <20>                 | <20>                 |
| Id                   | Kokonaisluku         | Yksilöllinen tunnus  |
| Pisteet              | Kokonaisluku 4-10    | Kayttajan kirjalle antamat pisteet |

#+LATEX: \noindent
Pistisiin liittyy automaattisesti generoituva id sekä yksittäistä arviota kuvaava kokonaisluku välillä 4-10. Pistetieto liittyy aina yhteen kirjaan sekä kyseiset pisteet antaneeseen käyttäjään.

*** Relaatiotietokantakaavio
#+BEGIN_LATEX
\begin{figure}[h]
\begin{center}
\includegraphics[width=1\textwidth]{/home/tapio/kritiikki/doc/relaatiotietokantakaavio.png}
\\ Relaatiotietokantakaavio
\end{center}
\end{figure}
#+END_LATEX
*** Järjestelmän yleisrakenne
*** Käyttöliittymä ja järjestelmän komponentit
**** Sivukartta
#+BEGIN_LATEX
\begin{figure}[h]
\begin{center}
\includegraphics[width=1.3\textwidth, angle =270]{/home/tapio/kritiikki/doc/sivukartta.jpg}
\vspace{5 mm} 
\\ Sivukartta
\end{center}
\end{figure}
#+END_LATEX
